# Generated by Django 3.2 on 2022-10-05 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['id'], 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(default='default author', help_text='выберите, на кого подписаться', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='auth.user', verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='subscription_date',
            field=models.DateField(auto_now_add=True, default='01.01', verbose_name='дата подписки'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_following'),
        ),
    ]
